# Data Wrangling in Python
# Using Data Wrangling concepts to clean a Netflix dataset available on Kaggle.
# Steps taken:
*  Uploading the Dataset
*  Discovery
*  Structuring
*  Cleaning
*  Transformation
*  Validate
*  Publishing

# 1: Upload the Dataset

In [1]:
import pandas as pd

In [2]:
import os
print(os.getcwd())

/kaggle/working

In [3]:
print(os.listdir("/kaggle/input"))

['netflix-shows']

In [4]:
df=pd.read_csv('/kaggle/input/netflix-shows/netflix_titles.csv')

# 2: Discovery

In [5]:
print(df.shape)
df.head()

(8807, 12)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [7]:
#To show the number of missing entries in each column
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [8]:
#To show the Percentage of missing entries in each column

df.isnull().mean()*100

show_id          0.000000
type             0.000000
title            0.000000
director        29.908028
cast             9.367549
country          9.435676
date_added       0.113546
release_year     0.000000
rating           0.045418
duration         0.034064
listed_in        0.000000
description      0.000000
dtype: float64

In [9]:
print(df['date_added'])
#Change format to datetime
df['date_added']=pd.to_datetime(df['date_added'],errors= 'coerce')

0       September 25, 2021
1       September 24, 2021
2       September 24, 2021
3       September 24, 2021
4       September 24, 2021
               ...
8802     November 20, 2019
8803          July 1, 2019
8804      November 1, 2019
8805      January 11, 2020
8806         March 2, 2019
Name: date_added, Length: 8807, dtype: object

In [10]:
print(df['date_added'])

0      2021-09-25
1      2021-09-24
2      2021-09-24
3      2021-09-24
4      2021-09-24
          ...
8802   2019-11-20
8803   2019-07-01
8804   2019-11-01
8805   2020-01-11
8806   2019-03-02
Name: date_added, Length: 8807, dtype: datetime64[ns]

In [11]:
#Export data to CSV
df.to_csv('Netflix_cleanDataset.csv', index=False)

# 3: Structuring

In [12]:
# Extract Year from date_added column into a new column(year_added) this is very useful for trend analyses
df['year_added']=df['date_added'].dt.year
print(df['year_added'])

0       2021.0
1       2021.0
2       2021.0
3       2021.0
4       2021.0
         ...
8802    2019.0
8803    2019.0
8804    2019.0
8805    2020.0
8806    2019.0
Name: year_added, Length: 8807, dtype: float64

In [13]:
#Removing Leading and Trailing spaces in director, cast and country columns

cat_columns=['director','cast','country']
df[cat_columns]=df[cat_columns].apply(lambda x:x.str.strip())

In [14]:
#Standardizing column names(To lowercase and replacing any spaces with underscores)
df.columns= df.columns.str.lower().str.replace(' ',"_")
print(df.columns.to_list())

['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description', 'year_added']

In [15]:
# Separated Duration into Numeric value and unit

df[['duration_value', 'duration_unit']]= df['duration'].str.extract(r'(\d+)\s*(\w+)')
print(df[['duration_value', 'duration_unit']])

     duration_value duration_unit
0                90           min
1                 2       Seasons
2                 1        Season
3                 1        Season
4                 2       Seasons
...             ...           ...
8802            158           min
8803              2       Seasons
8804             88           min
8805             88           min
8806            111           min

[8807 rows x 2 columns]

In [16]:
#Convert duration_value to Numeric
df['duration_value']=pd.to_numeric(df['duration_value'])
print(df[['duration_value', 'duration_unit']])

      duration_value duration_unit
0               90.0           min
1                2.0       Seasons
2                1.0        Season
3                1.0        Season
4                2.0       Seasons
...              ...           ...
8802           158.0           min
8803             2.0       Seasons
8804            88.0           min
8805            88.0           min
8806           111.0           min

[8807 rows x 2 columns]

# 4: Cleaning

In [17]:
#Check for Duplicates
#Gives the total Number of rows duplicated in the dataset
df.duplicated().sum()

0

In [18]:
#Drop Duplicates
df.drop_duplicates(inplace=True)
#df.shape
#df.info()

In [19]:
# Remove Irrelevant Information that will not be utilized for example description column
df= df.drop(columns=['description'])
#df.head()

In [20]:
# Impute Director values by using relationship between cast and director
df['dir_cast'] = df['director'] + '---' + df['cast']
#print(df['dir_cast'])
counts= df['dir_cast'].value_counts()# counts unique entries in dir_cast column

In [21]:
#check the number of entries repeated three or more times
filtered_counts=counts[counts >= 3]
filtered_values= filtered_counts.index
# print(counts)
# print(filtered_values)

In [22]:
lst_dir_cast=list(filtered_values)
dict_dircast= dict()
for i in lst_dir_cast:
    director,cast= i.split('---')
    dict_dircast[director]= cast
for i in range(len(dict_dircast)):
    df.loc[(df['director'].isna()) & (df['cast'] == list(dict_dircast.items())[i][1]),'director'] = list(dict_dircast.items())[i][0]

#Assign not given to all other director fields
df.loc[df['director'].isna(),'director'] = 'Not Given'
print(df['director'])

0       Kirsten Johnson
1             Not Given
2       Julien Leclercq
3             Not Given
4             Not Given
             ...
8802      David Fincher
8803          Not Given
8804    Ruben Fleischer
8805       Peter Hewitt
8806        Mozez Singh
Name: director, Length: 8807, dtype: object

In [23]:
# Use director to fill missing countries
directors= df['director']
countries=df['country']

# Pair each director with their country using zip() to get an iterator of tuples
pairs= zip(directors,countries)

#Convert the tuple into a dictionary
dir_cntry=dict(list(pairs))

#Fill the nulls in country with director matched their country values
for i in range(len(dir_cntry)):
    df.loc[(df['country'].isna()) & (df['director'] == list(dir_cntry.items())[i][0]),'country'] = list(dir_cntry.items())[i][1]

#Assign not given to all other country fields
df.loc[df['country'].isna(),'country']= 'Not Given'

print(df['country'].unique().tolist())

['United States', 'South Africa', 'France, Belgium', 'Not Given', 'India', 'United States, Ghana, Burkina Faso, United Kingdom, Germany, Ethiopia', 'United Kingdom', 'Germany, Czech Republic', 'Brazil', 'Mexico', 'Turkey', 'Australia', 'United States, India, France', 'Finland', 'China, Canada, United States', 'South Africa, United States, Japan', 'Nigeria', 'Japan', 'Germany', 'Spain, United States', 'France', 'Belgium', 'United Kingdom, United States', 'United States, United Kingdom', 'France, United States', 'South Korea', 'Spain', 'United States, Singapore', 'United States, Israel, United Kingdom, Canada', 'United States, Canada', 'United Kingdom, Australia, France', 'Philippines', 'United Kingdom, Australia, France, United States', 'Germany, United States', 'South Africa, United States', 'United States, Mexico', 'United States, Italy, France, Japan', 'United States, Italy, Romania, United Kingdom', 'Australia, United States', 'Argentina, Venezuela', 'United States, United Kingdom, Canada', 'China, Hong Kong', 'Russia', 'Canada', 'Hong Kong', 'United States, China, Hong Kong', 'Italy, United States', 'United States, Germany', 'United Kingdom, Canada, United States', ', South Korea', 'Ireland', 'India, Nepal', 'New Zealand, Australia, France, United States', 'Italy', 'Italy, Brazil, Greece', 'Argentina', 'Jordan', 'Colombia', 'United States, Japan', 'Belgium, United Kingdom', 'Switzerland, United Kingdom, Australia', 'Israel, United States', 'Canada, United States', 'Argentina, Spain', 'Taiwan', 'United States, Nigeria', 'Bulgaria, United States', 'Spain, United Kingdom, United States', 'United States, China', 'United States, France', 'Spain, France, United Kingdom, United States', ', France, Algeria', 'Poland', 'France, Israel, Germany, United States, United Kingdom', 'Mexico, Argentina', 'South Korea, United States', 'New Zealand', 'Egypt', 'Saudi Arabia', 'Thailand', 'Indonesia', 'Egypt, Denmark, Germany', 'United States, Switzerland', 'Hong Kong, Canada, United States', 'Kuwait, United States', 'France, Canada, United States, Spain', 'France, Netherlands, Singapore', 'Ireland, United States, United Kingdom', 'Malaysia', 'Israel', 'Australia, New Zealand', 'United Kingdom, Germany', 'Belgium, Netherlands', 'South Korea, Czech Republic', 'Australia, Germany', 'Vietnam', 'United Kingdom, Belgium', 'United Kingdom, Australia, United States', 'France, Japan, United States', 'United Kingdom, Germany, Spain, United States', 'United Kingdom, United States, France, Italy', 'United States, Germany, Canada', 'United States, France, Italy, United Kingdom', 'United States, United Kingdom, Germany, Hungary', 'United States, New Zealand', 'Sweden', 'China', 'Lebanon', 'Romania', 'Finland, Germany', 'Lebanon, Syria', 'Syria, France, Lebanon, Qatar', 'Iceland', 'Denmark', 'United States, India', 'Philippines, Singapore, Indonesia', 'China, United States, Canada', 'Lebanon, United Arab Emirates', 'Canada, United States, Denmark', 'United Arab Emirates', 'Mexico, France, Colombia', 'Netherlands', 'Germany, United States, France', 'United States, Bulgaria', 'United Kingdom, France, Germany, United States', 'Norway, Denmark', 'Egypt, France', 'United States, Czech Republic', 'Mauritius', 'Canada, South Africa', 'Austria', 'Mexico, Brazil', 'Germany, France', 'Mexico, United States', 'United Kingdom, France, Spain, United States', 'United States, Australia', 'United States, United Kingdom, France', 'United States, Russia', 'United States, United Kingdom, New Zealand', 'Australia, United Kingdom', 'Canada, Nigeria, United States', 'France, United States, United Kingdom, Canada', 'France, United Kingdom', 'India, United Kingdom', 'Canada, United States, Mexico', 'United Kingdom, Germany, United States', 'Czech Republic, United Kingdom, United States', 'China, United Kingdom', 'Italy, United Kingdom', 'China, Taiwan', 'United States, Brazil, Japan, Spain, India', 'United States, China, United Kingdom', 'Cameroon', 'Lebanon, Palestine, Denmark, Qatar', 'Japan, United States', 'Uruguay, Germany', 'Egypt, Saudi Arabia', 'United Kingdom, France, Poland, Germany, United States', 'Ireland, Switzerland, United Kingdom, France, United States', 'United Kingdom, South Africa, France', 'Ireland, United Kingdom, France, Germany', 'Russia, United States', 'United Kingdom, United States, France', 'United Kingdom,', 'United States, India, United Kingdom', 'Kenya', 'Spain, Argentina', 'India, United Kingdom, France, Qatar', 'Belgium, France', 'Argentina, Chile', 'United States, Thailand', 'Chile, Brazil', 'United States, Colombia', 'Canada, United States, United Kingdom', 'Uruguay', 'Luxembourg', 'United States, Cambodia, Romania', 'Bangladesh', 'Spain, Belgium, United States', 'United Kingdom, United States, Australia', 'Canada, United States, France', 'Portugal, United States', 'Portugal, Spain', 'India, United States', 'United Kingdom, Ireland', 'United Kingdom, Spain, United States', 'Hungary, United States', 'United States, South Korea', 'Canada, United States, Cayman Islands', 'India, France', 'France, Canada', 'Canada, Hungary, United States', 'Norway', 'Canada, United Kingdom, United States', 'United Kingdom, Germany, France, United States', 'Denmark, United States', 'Senegal', 'France, Algeria', 'United Kingdom, Finland, Germany, United States, Australia, Japan, France, Ireland', 'Philippines, Canada, United Kingdom, United States', 'Ireland, France, Iceland, United States, Mexico, Belgium, United Kingdom, Hong Kong', 'Singapore', 'Kuwait', 'United States, France, Serbia', 'United States, Italy', 'Spain, Italy', 'United States, Ireland, United Kingdom, India', 'United Kingdom, Singapore', 'Hong Kong, United States', 'United States, Malta, France, United Kingdom', 'United States, China, Canada', 'Canada, United States, Ireland', 'Lebanon, Canada, France', 'Japan, Canada, United States', 'Spain, France, Canada', 'Denmark, Singapore, Canada, United States', 'United States, France, Denmark', 'United States, China, Colombia', 'Spain, Thailand, United States', 'Mexico, Spain', 'Ireland, Luxembourg, Belgium', 'China, United States', 'Canada, Belgium', 'Canada, United Kingdom', 'Lebanon, United Arab Emirates, France, Switzerland, Germany', 'France, Belgium, Italy', 'Lebanon, United States, United Arab Emirates', 'Lebanon, France', 'France, Lebanon', 'France, Lebanon, United Kingdom', 'France, Norway, Lebanon, Belgium', 'Sweden, Czech Republic, United Kingdom, Denmark, Netherlands', 'United States, United Kingdom, India', 'Indonesia, Netherlands', 'Turkey, South Korea', 'Serbia, United States', 'Namibia', 'United Kingdom, Kenya', 'United Kingdom, France, Germany, Spain', 'United Kingdom, France, United States, Belgium, Luxembourg, China, Germany', 'Thailand, United States', 'United States, France, Canada, Belgium', 'United Kingdom, China', 'Germany, China, United Kingdom', 'Australia, New Zealand, United States', 'Hong Kong, Iceland, United States', 'France, Australia, Germany', 'United States, Belgium, Canada, France', 'South Africa, Angola', 'United States, Philippines', 'United States, United Kingdom, Canada, China', 'United States, Canada, United Kingdom', 'Turkey, United States', 'Peru, Germany, Norway', 'Mozambique', 'Brazil, France', 'China, Spain, South Korea, United States', 'Spain, Germany', 'Hong Kong, China', 'France, Belgium, Luxembourg, Cambodia,', 'United Kingdom, Australia', 'Belarus', 'Indonesia, United Kingdom', 'Switzerland, France, Belgium, United States', 'Ghana', 'Spain, France, Canada, United States', 'Chile, Italy', 'United Kingdom, Nigeria', 'Chile', 'France, Egypt', 'France, Brazil, Spain, Belgium', 'Egypt, Algeria', 'Canada, South Korea, United States', 'Nigeria, United Kingdom', 'United States, France, Canada', 'Poland, United States', 'United Arab Emirates, Jordan, Lebanon, Saudi Arabia', 'United States, Mexico, Spain, Malta', 'Saudi Arabia, United Arab Emirates', 'Zimbabwe', 'United Kingdom, Germany, United Arab Emirates, New Zealand', 'Romania, United States', 'Canada, Nigeria', 'Saudi Arabia, Netherlands, Germany, Jordan, United Arab Emirates, United States', 'United Kingdom, Spain', 'Finland, France', 'United Kingdom, Germany, United States, France', 'India, United Kingdom, China, Canada, Japan, South Korea, United States', 'Italy, United Kingdom, France', 'United States, Mexico, Colombia', 'Turkey, India', 'Italy, Turkey', 'United Kingdom, United States, Japan', 'France, Belgium, United States', 'Puerto Rico, United States, Colombia', 'Uruguay, Argentina', 'United States, United Kingdom, Japan', 'United States, Argentina', 'United Kingdom, Italy', 'Ireland, United Kingdom', 'United Kingdom, France, Belgium, Canada, United States', 'Netherlands, Germany, Denmark, United Kingdom', 'Hungary', 'Austria, Germany', 'Taiwan, China', 'United Kingdom, United States, Ireland', 'Brazil, United Kingdom', 'Pakistan, United States', 'Romania, France, Switzerland, Germany', 'Romania, United Kingdom', 'France, Malta, United States', 'Cyprus', 'United Kingdom, France, Belgium, Ireland, United States', 'United States, Norway, Canada', 'Kenya, United States', 'France, South Korea, Japan, United States', 'Taiwan, Malaysia', 'Uruguay, Argentina, Germany, Spain', 'United States, United Kingdom, France, Germany, Japan', 'United States, France, Japan', 'United Kingdom, France, United States', 'Spain, France, United States', 'Indonesia, South Korea, Singapore', 'United States, Spain', 'Netherlands, Germany, Italy, Canada', 'Spain, Germany, Denmark, United States', 'Norway, Sweden', 'South Korea, Canada, United States, China', 'Argentina, Uruguay, Serbia', 'France, Japan', 'Mauritius, South Africa', 'United States, Poland', 'United Kingdom, United States, Germany, Denmark, Belgium, Japan', 'India, Germany', 'India, United Kingdom, Canada, United States', 'Philippines, United States', 'Romania, Bulgaria, Hungary', 'Uruguay, Guatemala', 'France, Senegal, Belgium', 'United Kingdom, Canada', 'Mexico, United States, Spain, Colombia', 'Canada, Norway', 'Singapore, United States', 'Finland, Germany, Belgium', 'United Kingdom, France', 'United States, Chile', 'United Kingdom, Japan, United States', 'Spain, United Kingdom', 'Argentina, United States, Mexico', 'United States, South Korea, Japan', 'Canada, Australia', 'United Kingdom, Hungary, Australia', 'Italy, Belgium', 'United States, United Kingdom, Germany', 'Switzerland', 'Singapore, Malaysia', 'France, Belgium, Luxembourg, Romania, Canada, United States', 'South Africa, Nigeria', 'Spain, France', 'United Kingdom, Hong Kong', 'Pakistan', 'Brazil, United States', 'Denmark, Brazil, France, Portugal, Sweden', 'India, Turkey', 'Malaysia, Singapore, Hong Kong', 'Philippines, Singapore', 'Australia, Canada', 'Taiwan, China, France, United States', 'Germany, Italy', 'Colombia, Peru, United Kingdom', 'Thailand, China, United States', 'Argentina, United States', 'Sweden, United States', 'Uruguay, Spain, Mexico', 'France, Luxembourg, Canada', 'Denmark, Spain', 'Chile, Argentina', 'United Kingdom, Belgium, Sweden', 'Canada, Brazil', 'Italy, France', 'Canada, Germany', 'Pakistan, United Arab Emirates', 'Ghana, United States', 'Mexico, Finland', 'United Arab Emirates, United Kingdom, India', 'Netherlands, Belgium', 'United States, Taiwan', 'Austria, Iraq, United States', 'United Kingdom, Malawi', 'Paraguay, Argentina', 'United Kingdom, Russia, United States', 'India, Pakistan', 'Indonesia, Singapore', 'Spain, Belgium', 'Iceland, Sweden, Belgium', 'Croatia', 'Uruguay, Argentina, Spain', 'United Kingdom, Ireland, United States', 'Canada, Germany, France, United States', 'United Kingdom, Japan', 'Norway, Denmark, Netherlands, Sweden', 'Hong Kong, China, United States', 'Ireland, Canada', 'Italy, Switzerland, France, Germany', 'Mexico, Netherlands', 'United States, Sweden', 'Germany, France, Russia', 'France, Iran, United States', 'United Kingdom, India', 'Russia, Poland, Serbia', 'Spain, Portugal', 'Peru', 'United Kingdom, Canada, United States, Cayman Islands', 'Indonesia, United States', 'Norway, Iceland, United States', 'Czech Republic, United States', 'United Kingdom, India, United States', 'United Kingdom, West Germany', 'India, Australia', 'United States,', 'Belgium, United Kingdom, United States', 'India, Germany, Austria', 'United States, Brazil, South Korea, Mexico, Japan, Germany', 'Spain, Mexico', 'China, Japan', 'Argentina, France', 'China, United States, United Kingdom', 'France, Luxembourg, United States', 'China, United States, Australia', 'Colombia, Mexico', 'United States, Canada, Ireland', 'Chile, Peru', 'Argentina, Italy', 'Canada, Japan, United States', 'United Kingdom, Canada, United States, Germany', 'Italy, Switzerland, Albania, Poland', 'United States, Japan, Canada', 'Cambodia', 'Italy, United States, Argentina', 'Saudi Arabia, Syria, Egypt, Lebanon, Kuwait', 'United States, Canada, Indonesia, United Kingdom, China, Singapore', 'Spain, Colombia', 'United Kingdom, South Africa, Australia, United States', 'Bulgaria', 'Argentina, Brazil, France, Poland, Germany, Denmark', 'United Kingdom, Spain, United States, Germany', 'Philippines, Qatar', 'Netherlands, Belgium, Germany, Jordan', 'United Arab Emirates, United States', 'Norway, Germany, Sweden', 'South Korea, China', 'Georgia', 'Soviet Union, India', 'Australia, United Arab Emirates', 'Canada, Germany, South Africa', 'South Korea, China, United States', 'India, Soviet Union', 'India, Mexico', 'Georgia, Germany, France', 'United Arab Emirates, Romania', 'India, Malaysia', 'Germany, Jordan, Netherlands', 'Turkey, France, Germany, Poland', 'Greece, United States', 'France, United Kingdom, United States', 'Norway, Germany', 'France, Morocco', 'Cambodia, United States', 'United States, Denmark', 'United States, Colombia, Mexico', 'United Kingdom, Italy, Israel, Peru, United States', 'Argentina, Uruguay, Spain, France', 'United Kingdom, France, United States, Belgium', 'France, Canada, China, Cambodia', 'United Kingdom, France, Belgium, United States', 'Chile, France', 'Netherlands, United States', 'France, United Kingdom, India', 'Czech Republic, Slovakia', 'Singapore, France', 'Spain, Switzerland', 'United States, Australia, China', 'South Africa, United States, Germany', 'United States, United Kingdom, Australia', 'Spain, Italy, Argentina', 'Chile, Spain, Argentina, Germany', 'West Germany', 'Austria, Czech Republic', 'Lebanon, Qatar', 'United Kingdom, Jordan, Qatar, Iran', 'France, South Korea, Japan', 'Israel, Germany, France', 'Canada, Japan, Netherlands', 'United States, Hungary', 'France, Germany', 'France, Qatar', 'United Kingdom, Germany, Canada', 'Ireland, South Africa', 'Chile, United States, France', 'Belgium, France, Netherlands', 'United Kingdom, Ukraine, United States', 'Germany, Australia, France, China', 'Norway, United States', 'United States, Bermuda, Ecuador', 'United States, Hungary, Ireland, Canada', 'United Kingdom, Egypt, United States', 'United States, France, United Kingdom', 'Spain, Mexico, France', 'United States, South Africa', 'Hong Kong, China, Singapore', 'South Africa, China, United States', 'Denmark, France, Poland', 'New Zealand, United Kingdom', 'Netherlands, Denmark, South Africa', 'Iran, France', 'United Kingdom, United States, France, Germany', 'Australia, France', 'Ireland, United Kingdom, United States', 'United Kingdom, France, Germany', 'Canada, Luxembourg', 'Brazil, Netherlands, United States, Colombia, Austria, Germany', 'France, Canada, Belgium', 'Canada, France', 'Bulgaria, United States, Spain, Canada', 'Sweden, Netherlands', 'France, United States, Mexico', 'Australia, United Kingdom, United Arab Emirates, Canada', 'Australia, Armenia, Japan, Jordan, Mexico, Mongolia, New Zealand, Philippines, South Africa, Sweden, United States, Uruguay', 'India, Iran', 'France, Belgium, Spain', 'Denmark, Sweden, Israel, United States', 'United States, Iceland', 'United Kingdom, Russia', 'United States, Israel, Italy, South Africa', 'Netherlands, Denmark, France, Germany', 'South Korea, Japan', 'United Kingdom, Pakistan', 'France, New Zealand', 'United Kingdom, Czech Republic, United States, Germany, Bahamas', 'China, Germany, India, United States', 'Germany, Sri Lanka', 'United States, India, Bangladesh', 'United States, Canada, France', 'Brazil, France, Germany', 'Germany, United States, Hong Kong, Singapore', 'France, Germany, Switzerland', 'Germany, France, Luxembourg, United Kingdom, United States', 'United Kingdom, Canada, Italy', 'Czech Republic, France', 'Taiwan, Hong Kong, United States, China', 'Germany, Australia', 'United Kingdom, Poland, United States', 'Denmark, Zimbabwe', 'United Kingdom, South Africa', 'Finland, Sweden, Norway, Latvia, Germany', 'South Africa, United States, New Zealand, Canada', 'United States, Italy, United Kingdom, Liechtenstein', 'Denmark, France, Belgium, Italy, Netherlands, United States, United Kingdom', 'United States, Australia, Mexico', 'United Kingdom, Czech Republic, Germany, United States', 'France, China, Japan, United States', 'United States, South Korea, China', 'Germany, Belgium', 'Pakistan, Norway, United States', 'United States, Canada, Belgium, United Kingdom', 'Venezuela', 'Canada, France, Italy, Morocco, United States', 'Canada, Spain, France', 'United States, Indonesia', 'Spain, France, Italy', 'United Arab Emirates, United States, United Kingdom', 'United Kingdom, Israel, Russia', 'Spain, Cuba', 'United States, Brazil', 'United States, France, Mexico', 'United States, Nicaragua', 'United Kingdom, United States, Spain, Germany, Greece, Canada', 'Italy, Canada, France', 'United Kingdom, Denmark, Canada, Croatia', 'Italy, Germany', 'United States, France, United Kingdom, Japan', 'United States, United Kingdom, Denmark, Sweden', 'United States, United Kingdom, Italy', 'United States, France, Canada, Spain', 'Russia, United States, China', 'United States, Canada, Germany', 'Ireland, United States', 'United States, United Arab Emirates', 'United States, Ireland', 'Ireland, United Kingdom, Italy, United States', 'Poland,', 'Slovenia, Croatia, Germany, Czech Republic, Qatar', 'Canada, United Kingdom, Netherlands', 'United States, Spain, Germany', 'India, Japan', 'China, South Korea, United States', 'United Kingdom, France, Belgium', 'Canada, Ireland, United States', 'United Kingdom, United States, Dominican Republic', 'United States, Senegal', 'Germany, United Kingdom, United States', 'South Africa, Germany, Netherlands, France', 'Canada, United States, United Kingdom, France, Luxembourg', 'Ireland, United States, France', 'Germany, United States, Canada', 'United Kingdom, Germany, Canada, United States', 'United States, France, Canada, Lebanon, Qatar', 'Netherlands, Belgium, United Kingdom, United States', 'France, Belgium, China, United States', 'United States, Chile, Israel', 'United Kingdom, Norway, Denmark, Germany, Sweden', 'Norway, Denmark, Sweden', 'China, India, Nepal', 'Colombia, Mexico, United States', 'United Kingdom, South Korea', 'Denmark, China', 'United States, Greece, Brazil', 'South Korea, France', 'United States, Australia, Samoa, United Kingdom', 'Germany, United Kingdom', 'Argentina, Chile, Peru', 'Turkey, Azerbaijan', 'Poland, West Germany', 'Germany, United States, Sweden', 'Canada, Spain', 'United States, Cambodia', 'United States, Greece', 'Norway, United Kingdom, France, Ireland', 'United Kingdom, Poland', 'Israel, Sweden, Germany, Netherlands', 'Switzerland, France', 'Italy, India', 'United States, Botswana', 'Chile, Argentina, France, Spain, United States', 'United States, India, South Korea, China', 'Denmark, Germany, Belgium, United Kingdom, France', 'Denmark, Germany, Belgium, United Kingdom, France, Sweden', 'France, Switzerland, Spain, United States, United Arab Emirates', 'Brazil, India, China, United States', 'Denmark, France, United States, Sweden', 'Australia, Iraq', 'China, Morocco, Hong Kong', 'Canada, United States, Germany', 'United Kingdom, Thailand', 'Venezuela, Colombia', 'Colombia, United States', 'France, Germany, C

In [24]:
# Assign Not given to all other fields
df.loc[df['cast'].isna(),'cast'] = 'Not Given'

In [25]:
#Drop other row records that are null

df.drop(df[df['date_added'].isna()].index,axis=0,inplace=True)
df.drop(df[df['rating'].isna()].index,axis=0,inplace=True)
df.drop(df[df['duration'].isna()].index,axis=0,inplace=True)

In [26]:
print(df.shape)

(8702, 15)

  * Fixing Errors

In [28]:
# Checking if there are added days that come before release_year
import datetime as dt

sum(df['date_added'].dt.year<df['release_year'])
df.loc[(df['date_added'].dt.year < df['release_year']),['date_added','release_year']]
# sample some of the records and check that they have been accurately replaced
df.iloc[[1551,1696,2920,3168]]
#Confirm that no more release_year inconsistencies
sum(df['date_added'].dt.year < df['release_year'])

14

# 5: Transformation

In [38]:
# separate columns for listed_in to analyze separately
# Check maximum Number of categories in listed_in column
max(df['listed_in'].str.split(',').apply(lambda x: len(x)))

3

In [40]:
# Creating 3 new columns to store the splitted listed_in column
df['listed_in_1']=df['listed_in'].str.split(',', expand = True)[0]
df['listed_in_2']=df['listed_in'].str.split(',', expand = True)[1]
df['listed_in_3']=df['listed_in'].str.split(',', expand = True)[2]
print(df[['listed_in_1','listed_in_2','listed_in_3']].head())

              listed_in_1              listed_in_2             listed_in_3
0           Documentaries                     None                    None
1  International TV Shows                TV Dramas            TV Mysteries
2          Crime TV Shows   International TV Shows   TV Action & Adventure
3              Docuseries               Reality TV                    None
4  International TV Shows        Romantic TV Shows             TV Comedies

# 6: Validation

In [30]:
# Removing Columns formed during data Wrangling
df.drop(columns=['dir_cast'], inplace=True)

In [31]:
# Exporting data to CSV to Check the consistency, accuracy, and completeness of the data

df.to_csv('Netflix_cleanDataset2.csv', index=False)

In [32]:
# Ensuring each column has the correct data type 
df.dtypes

show_id                   object
type                      object
title                     object
director                  object
cast                      object
country                   object
date_added        datetime64[ns]
release_year               int64
rating                    object
duration                  object
listed_in                 object
year_added               float64
duration_value           float64
duration_unit             object
dtype: object

In [33]:
# Using business logic or sanity rules to identify anomalies e.g. records before 1997
anomalies = df[df['year_added']<1997]
print(anomalies[['date_added','year_added']].head())

#No records before 1997

Empty DataFrame
Columns: [date_added, year_added]
Index: []

In [34]:
# Ensuring no Important Fields are missing
df.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,year_added,duration_value,duration_unit
8008,s8009,Movie,Shorgul,"Jitendra Tiwari, Pranav Singh","Ashutosh Rana, Jimmy Shergill, Suha Gezen, San...",India,2018-10-30,2016,TV-14,122 min,"Dramas, International Movies",2018.0,122.0,min
7007,s7008,Movie,Hotel Pacific,Janusz Majewski,"Marek Kondrat, Roman Wilhelmi, Roman Skamene, ...","Poland,",2019-10-01,1975,TV-MA,96 min,"Classic Movies, Dramas, International Movies",2019.0,96.0,min
8049,s8050,Movie,Soekarno,Hanung Bramantyo,"Ario Bayu, Lukman Sardi, Maudy Koesnaedi, Tant...",Indonesia,2019-01-05,2013,TV-MA,142 min,"Dramas, International Movies",2019.0,142.0,min
2058,s2059,TV Show,The Witcher: A Look Inside the Episodes,Not Given,"Henry Cavill, Anya Chalotra, Freya Allan, Laur...",Not Given,2020-09-02,2020,TV-MA,1 Season,"Docuseries, TV Sci-Fi & Fantasy",2020.0,1.0,Season
704,s705,Movie,A Man For The Week End,Achille Brice,"Syndy Emade, Alexx Ekubo, Solange Ojong, Nchif...",Not Given,2021-06-16,2018,TV-14,95 min,"Comedies, Dramas, International Movies",2021.0,95.0,min

In [36]:
# Reset the Index Useful when the DataFrame index has become messy e.g., after filtering or concatenation.
df_reset = df.reset_index(drop=True)

# 7: Publish

In [37]:
# Save the dataset as csv

df.to_csv('/kaggle/working/Cleaned_netflix.csv', index= False)